# Generated by Django 2.2.6 on 2020-06-15 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Admission number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Form', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='kcpe',
            field=models.IntegerField(verbose_name='Kcpe Marks'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.CharField(max_length=200, verbose_name='Passport Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=30, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream_id',
            field=models.IntegerField(verbose_name='Stream'),
        ),
    ]
