# Generated by Django 3.0.8 on 2020-07-21 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Admission number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='kcpe',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Kcpe Marks'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(max_length=200, upload_to='passports/', verbose_name='Passport Photo'),
        ),
    ]
