# Generated by Django 3.0.8 on 2020-07-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200721_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.FileField(max_length=200, upload_to='passports/', verbose_name='Passport Photo'),
        ),
    ]
