# Generated by Django 3.0.8 on 2020-07-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200721_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Admission number'),
        ),
    ]
