# Generated by Django 2.2.6 on 2020-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.IntegerField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=10)),
            ],
        ),
    ]
