# Generated by Django 2.2.6 on 2020-06-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_name',
            field=models.TextField(max_length=10, verbose_name='Forn name'),
        ),
    ]
