# Generated by Django 2.2.6 on 2020-06-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200616_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Forms',
        ),
    ]
