# Generated by Django 3.0.8 on 2020-07-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200616_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='form_name',
            field=models.TextField(max_length=10, verbose_name='Form name'),
        ),
    ]
