# Generated by Django 3.0.8 on 2020-07-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Stream')),
                ('subject_name', models.CharField(max_length=20, unique=True, verbose_name='Subject')),
                ('optionality', models.BooleanField(verbose_name='Optionality')),
            ],
        ),
    ]
