# Generated by Django 3.0.8 on 2020-07-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Stream')),
                ('stream_name', models.TextField(max_length=10, verbose_name='Stream')),
            ],
        ),
    ]
